### ISSUE TITLE
Adding Checkboxes

### ISSUE THREAD

**Issue by MananShukla** [ajk77/SimpleEMRSystem#4]
Hi,

Thanks for such a wonderful library! I have a quick question: in your powerpoint, I have seen the ability to add checkboxes and hide certain charts. Can you please let me know where this functionality is implemented, and how it is done?

Please let me know the steps I need to take- I would really appreciate it!

Thanks,
Manan

**Comment by ajk77** [comment]
Hi Manan, 

The checkboxes are turned on and off using a parameter called "show_checkboxes".  You will see it as "{% if show_checkboxes %}" in SimpleEMRSystem/SEMRinterface/templates/SEMRinterface/case_viewer.html. 

When show_checkboxes is true, a <span> containing the checkboxes are added to each data element using javascript (i.e., the create_selection_screen function in SimpleEMRSystem/SEMRinterface/static/js/emr_3.js). 

After a user selects their checkboxes, the result is stored in: SimpleEMRSystem/resources/demo_study/stored_results.txt. 

To configure the checkbox workflow for an individual case, you need edit SimpleEMRSystem/resources/demo_study/case_details.json. Here you will see a dictionary of cases where each case has a list of different display settings. Each entry in the list is a "time_step". The default cases are configured to be displayed twice: at the first index (corresponding to time_step 0) "check_boxes" = 0 and at the second index (corresponding to time_step 1) "check_boxes" = 1. You can configure your cases to have as many time steps as you want. 

The last piece of this is: "how does the system keep track of which user, case, and time_step should be shown at any given moment?" This is all done through the URL. See SimpleEMRSystem/SEMRinterface/urls.py and the case_viewer function of SimpleEMRSystem/SEMRinterface/views.py to see how this is handled. 

Your second question was about hiding particular data elements. The easiest way to do this is to create two versions of case where one version has all the data and the second version has a reduced set of data. For example, if you had a case 1234, you can create two versions of it: 1234a and 1234b. You will define both versions in case_details.json and the cases_all directory. Then adjust your user assignments in user_details.json.  (Depending on your needs, you could implement other solutions as well.) 

Hope this helps.
Andrew
